### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.

### CODE REVIEW

**Comment by kianmeng** [comment]
@tmjoen Should I resolve the conflict and resubmit the PR again?

**Comment by tmjoen** [comment]
Hi @kianmeng,

yes, that would be great! Sorry I missed this PR completely!

**Comment by kianmeng** [comment]
@tmjoen Done. Please check.

**Comment by tmjoen** [comment]
Thanks so much!

**Comment by kianmeng** [comment]
:+1: :tada:

**Pull request merged**
